#!/bin/bash
# Tube OS installer - runs in background, writes progress to log
set -e

LOG="/tmp/tubeos-install.log"
MARKER="/tmp/tubeos-install.json"

log() { echo "$(date +%H:%M:%S) $1" >> "$LOG"; }

if [ ! -f "$MARKER" ]; then
    log "INSTALL_FAIL: No install marker found"
    exit 1
fi

DISK=$(python3 -c "import json; print(json.load(open('$MARKER'))['disk'])")
HOSTNAME=$(python3 -c "import json; print(json.load(open('$MARKER'))['hostname'])")

# Determine partition naming (e.g. /dev/nvme0n1p1 vs /dev/sda1)
if [[ "$DISK" =~ [0-9]$ ]]; then
    PART_EFI="${DISK}p1"
    PART_ROOT="${DISK}p2"
else
    PART_EFI="${DISK}1"
    PART_ROOT="${DISK}2"
fi

log "Starting installation to $DISK (EFI: $PART_EFI, Root: $PART_ROOT)"
log "Partitioning $DISK"

# Unmount existing mounts if any
umount -f "$PART_EFI" 2>/dev/null || true
umount -f "$PART_ROOT" 2>/dev/null || true
umount -f /mnt/boot/efi 2>/dev/null || true
umount -f /mnt 2>/dev/null || true

# Partition
parted -s "$DISK" mklabel gpt
parted -s "$DISK" mkpart ESP fat32 1MiB 513MiB
parted -s "$DISK" set 1 esp on
parted -s "$DISK" mkpart root ext4 513MiB 100%
partprobe "$DISK" 2>/dev/null || true
udevadm settle 2>/dev/null || sleep 2
log "Partitioning done"

# Format
mkfs.vfat -F32 "$PART_EFI"
mkfs.ext4 -F -L tubeos-root "$PART_ROOT"
log "Filesystems created"

# Mount
mount "$PART_ROOT" /mnt
mkdir -p /mnt/boot/efi
mount "$PART_EFI" /mnt/boot/efi
log "Filesystems mounted"

# Copy system
rsync -ax --exclude='/dev/*' --exclude='/proc/*' --exclude='/sys/*' \
    --exclude='/tmp/*' --exclude='/run/*' --exclude='/mnt/*' \
    --exclude='/boot/efi/*' / /mnt/
log "System copied"

# Mount pseudo-filesystems for chroot
mount --make-rslave /mnt 2>/dev/null || true
mount -t proc proc /mnt/proc
mount -t sysfs sys /mnt/sys
mount --bind /dev /mnt/dev
mount --make-rslave /mnt/dev 2>/dev/null || true
mkdir -p /mnt/dev/pts
mount -t devpts devpts /mnt/dev/pts -o ptmxmode=0666,nosuid,noexec 2>/dev/null || mount --bind /dev/pts /mnt/dev/pts
mount --make-rslave /mnt/dev/pts 2>/dev/null || true
if [ -d /sys/firmware/efi ] && [ -d /sys/firmware/efi/efivars ]; then
    mkdir -p /mnt/sys/firmware/efi/efivars
    mount --bind /sys/firmware/efi/efivars /mnt/sys/firmware/efi/efivars 2>/dev/null || true
    mount --make-rslave /mnt/sys/firmware/efi/efivars 2>/dev/null || true
fi

run_chroot() {
    if command -v arch-chroot >/dev/null 2>&1; then
        arch-chroot /mnt "$@"
    else
        chroot /mnt "$@"
    fi
}

# Regenerate initramfs
if [ -f /mnt/etc/pacman.conf ]; then
    rm -f /mnt/etc/mkinitcpio.conf.d/archiso.conf 2>/dev/null || true
    mkdir -p /mnt/etc/mkinitcpio.conf.d
    echo "HOOKS=(base udev autodetect modconf kms keyboard keymap consolefont plymouth block filesystems fsck)" > /mnt/etc/mkinitcpio.conf.d/tubeos.conf
    run_chroot mkinitcpio -P 2>&1 || true
else
    run_chroot update-initramfs -u -k all 2>&1 || true
fi

# Bootloader
log "Writing /etc/default/grub configuration"
cat > /mnt/etc/default/grub << GRUBEOF
# /etc/default/grub - generated by Tube OS installer
GRUB_DEFAULT="0"
GRUB_TIMEOUT="5"
GRUB_DISTRIBUTOR="Tube OS"
GRUB_CMDLINE_LINUX=""
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
GRUB_DISABLE_OS_PROBER="false"
GRUB_ENABLE_CRYPTODISK="false"
GRUBEOF

# Install os-prober
IS_EFI=false
[ -d /sys/firmware/efi ] && IS_EFI=true

if [ -d /sys/firmware/efi ]; then
    if command -v pacman >/dev/null 2>&1 && [ -f /mnt/etc/pacman.conf ]; then
        run_chroot pacman -S --noconfirm --needed os-prober grub efibootmgr 2>/dev/null || true
    else
        run_chroot apt-get install -y --no-install-recommends grub-efi-amd64 os-prober 2>/dev/null || true
    fi
else
    if command -v pacman >/dev/null 2>&1 && [ -f /mnt/etc/pacman.conf ]; then
        run_chroot pacman -S --noconfirm --needed os-prober grub 2>/dev/null || true
    else
        run_chroot apt-get install -y --no-install-recommends grub-pc os-prober 2>/dev/null || true
    fi
fi

if $IS_EFI; then
    log "Installing GRUB UEFI to $DISK"
    if ! run_chroot grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=TubeOS --recheck; then
        log "GRUB UEFI (TubeOS id) failed, will rely on --removable copy"
    fi
    if ! run_chroot grub-install --target=x86_64-efi --efi-directory=/boot/efi --removable --recheck; then
        log "WARNING: GRUB UEFI --removable failed"
    fi
    # Ensure UEFI Default Fallback path exists (critical for QEMU/VMs without NVRAM)
    mkdir -p /mnt/boot/efi/EFI/BOOT
    if [ -f /mnt/boot/efi/EFI/TubeOS/grubx64.efi ]; then
        cp -f /mnt/boot/efi/EFI/TubeOS/grubx64.efi /mnt/boot/efi/EFI/BOOT/BOOTX64.EFI
        cp -f /mnt/boot/efi/EFI/TubeOS/grubx64.efi /mnt/boot/efi/EFI/BOOT/bootx64.efi
        log "UEFI fallback bootloader written to EFI/BOOT"
    elif [ -f /mnt/boot/efi/EFI/BOOT/grubx64.efi ]; then
        cp -f /mnt/boot/efi/EFI/BOOT/grubx64.efi /mnt/boot/efi/EFI/BOOT/BOOTX64.EFI
        cp -f /mnt/boot/efi/EFI/BOOT/grubx64.efi /mnt/boot/efi/EFI/BOOT/bootx64.efi
        log "UEFI fallback bootloader written to EFI/BOOT"
    else
        log "WARNING: no grubx64.efi found on ESP; UEFI fallback not written"
    fi
else
    log "Installing GRUB BIOS/MBR to $DISK"
    if ! run_chroot grub-install --target=i386-pc "$DISK" --recheck; then
        log "WARNING: GRUB i386-pc install failed"
    fi
fi

log "Generating GRUB menu (grub-mkconfig)"
if ! run_chroot grub-mkconfig -o /boot/grub/grub.cfg; then
    log "WARNING: grub-mkconfig failed, retrying with update-grub"
    run_chroot update-grub || log "WARNING: update-grub also failed"
fi

if [ -s /mnt/boot/grub/grub.cfg ] && grep -q 'menuentry ' /mnt/boot/grub/grub.cfg; then
    log "Bootloader installed and GRUB menu generated"
else
    log "FATAL: /boot/grub/grub.cfg missing or empty after grub-mkconfig"
fi

# Fstab
if command -v genfstab >/dev/null 2>&1; then
    genfstab -U /mnt >> /mnt/etc/fstab
else
    ROOT_UUID=$(blkid -s UUID -o value "$PART_ROOT" || true)
    EFI_UUID=$(blkid -s UUID -o value "$PART_EFI" || true)
    cat <<EOF >> /mnt/etc/fstab
UUID=$ROOT_UUID / ext4 errors=remount-ro 0 1
UUID=$EFI_UUID /boot/efi vfat umask=0077 0 2
EOF
fi
log "fstab generated"

# Clean unselected desktop sessions (remove GNOME, Openbox, Kodi on GBM, etc.)
log "Cleaning unused desktop sessions"
for sdir in /mnt/usr/share/xsessions /mnt/usr/share/wayland-sessions; do
    if [ -d "$sdir" ]; then
        for f in "$sdir"/*.desktop; do
            [ -f "$f" ] || continue
            fname=$(basename "$f")
            if [ "$fname" != "plasma-bigscreen-wayland.desktop" ] && [ "$fname" != "plasma-bigscreen.desktop" ]; then
                rm -f "$f"
                log "Removed extra session: $fname"
            fi
        done
    fi
done

# Purge Kodi desktop files
rm -f /mnt/usr/share/xsessions/kodi.desktop /mnt/usr/share/wayland-sessions/kodi-gbm.desktop /mnt/usr/share/wayland-sessions/kodi-wayland.desktop /mnt/usr/share/applications/kodi.desktop 2>/dev/null || true

# User setup with explicit home & permissions
USERNAME="tubeos"
PASSWORD="tubeos"
if [ -f "$MARKER" ]; then
    USERNAME=$(python3 -c "import json; print(json.load(open('$MARKER')).get('username', 'tubeos'))" 2>/dev/null || echo "tubeos")
    PASSWORD=$(python3 -c "import json; print(json.load(open('$MARKER')).get('password', 'tubeos'))" 2>/dev/null || echo "tubeos")
fi

# Sync passwd/shadow before user modifications
run_chroot pwconv 2>/dev/null || true
run_chroot grpconv 2>/dev/null || true

# Purge leftover base image users (live, pulsar, alarm, arch, tubeos)
if [ -f /mnt/etc/passwd ]; then
    while IFS=: read -r uname _ u_uid _; do
        if [ "$uname" = "live" ] || [ "$uname" = "alarm" ] || [ "$uname" = "pulsar" ] || [ "$uname" = "arch" ] || [ "$uname" = "tubeos" ] || { [ "$u_uid" -ge 1000 ] 2>/dev/null && [ "$uname" != "$USERNAME" ]; }; then
            log "Removing leftover user: $uname"
            run_chroot userdel -r -f "$uname" 2>/dev/null || true
            rm -rf "/mnt/home/$uname" 2>/dev/null || true
        fi
    done < /mnt/etc/passwd
fi

# Clean leftover groups
for lgrp in live alarm pulsar arch tubeos; do
    run_chroot groupdel "$lgrp" 2>/dev/null || true
done

# Create group and user explicitly
run_chroot groupadd -g 1000 -f "$USERNAME" 2>/dev/null || run_chroot groupadd -f "$USERNAME" 2>/dev/null || true
run_chroot id -u "$USERNAME" >/dev/null 2>&1 || run_chroot useradd -m -u 1000 -g "$USERNAME" -s /bin/bash "$USERNAME" 2>/dev/null || run_chroot useradd -m -s /bin/bash "$USERNAME" 2>/dev/null || true

# Failsafe guarantee: ensure user is 100% in /etc/passwd and /etc/shadow
if ! run_chroot id -u "$USERNAME" >/dev/null 2>&1; then
    echo "$USERNAME:x:1000:" >> /mnt/etc/group
    echo "$USERNAME:x:1000:1000::/home/$USERNAME:/bin/bash" >> /mnt/etc/passwd
    run_chroot pwconv 2>/dev/null || true
fi

# Add groups safely
for grp in wheel sudo docker audio video input render storage power; do
    run_chroot groupadd -f "$grp" 2>/dev/null || true
    run_chroot usermod -aG "$grp" "$USERNAME" 2>/dev/null || true
done

run_chroot usermod -s /bin/bash "$USERNAME" 2>/dev/null || true
run_chroot mkdir -p "/home/$USERNAME"
run_chroot chown -R "$USERNAME:$USERNAME" "/home/$USERNAME" 2>/dev/null || run_chroot chown -R 1000:1000 "/home/$USERNAME" 2>/dev/null || true
run_chroot chmod 755 "/home/$USERNAME"

# Set passwords via chpasswd and direct shadow hash update
echo "$USERNAME:$PASSWORD" | run_chroot chpasswd
echo "root:$PASSWORD" | run_chroot chpasswd

run_chroot pwconv 2>/dev/null || true
if command -v openssl >/dev/null 2>&1; then
    PASS_HASH=$(openssl passwd -6 "$PASSWORD" 2>/dev/null || true)
    if [ -n "$PASS_HASH" ]; then
        run_chroot usermod -p "$PASS_HASH" "$USERNAME" 2>/dev/null || true
        run_chroot usermod -p "$PASS_HASH" root 2>/dev/null || true
    fi
fi
run_chroot chage -d "$(date +%Y-%m-%d)" "$USERNAME" 2>/dev/null || true
run_chroot chage -E -1 -M 99999 "$USERNAME" 2>/dev/null || true

# Clean unselected desktop sessions and launchers
rm -f /mnt/usr/share/xsessions/kodi.desktop /mnt/usr/share/wayland-sessions/kodi-gbm.desktop /mnt/usr/share/wayland-sessions/kodi-wayland.desktop /mnt/usr/share/applications/kodi.desktop 2>/dev/null || true

# Create reliable plasma-bigscreen-session launcher script
cat > /mnt/usr/bin/plasma-bigscreen-session << 'LAUNCHEOF'
#!/bin/sh
export PLASMA_DEFAULT_SHELL=org.kde.plasma.bigscreen
export KDE_LOOKANDFEEL=org.kde.plasma.bigscreen
export QT_QPA_PLATFORM=wayland
export KDE_FULL_SESSION=true
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_DESKTOP=KDE
export XDG_SESSION_TYPE=wayland
export QT_QUICK_CONTROLS_STYLE=Plasma
export PLASMA_SHELL_PACKAGE=org.kde.plasma.bigscreen

# Launch plasma-bigscreen-inputhandler in background if available
for handler in /usr/bin/plasma-bigscreen-inputhandler /usr/lib/plasma-bigscreen-inputhandler /usr/libexec/plasma-bigscreen-inputhandler; do
    if [ -x "$handler" ]; then
        pgrep -f plasma-bigscreen-inputhandler >/dev/null || "$handler" &
        break
    fi
done

for exe in /usr/bin/plasma-bigscreen-wayland /usr/lib/plasma-bigscreen-wayland /usr/libexec/plasma-bigscreen-wayland; do
    if [ -x "$exe" ]; then
        exec "$exe"
    fi
done
if [ -f /usr/lib/plasma-bigscreen-common-env ]; then
    . /usr/lib/plasma-bigscreen-common-env
    exec /usr/bin/startplasma-wayland --xwayland --libinput
elif [ -f /usr/bin/plasma-bigscreen-common-env ]; then
    . /usr/bin/plasma-bigscreen-common-env
    exec /usr/bin/startplasma-wayland --xwayland --libinput
else
    exec /usr/bin/startplasma-wayland
fi
LAUNCHEOF
chmod 0755 /mnt/usr/bin/plasma-bigscreen-session

# Autostart plasma-bigscreen-inputhandler in XDG autostart
mkdir -p /mnt/etc/xdg/autostart
cat > /mnt/etc/xdg/autostart/plasma-bigscreen-inputhandler.desktop << 'AUTOEOF'
[Desktop Entry]
Type=Application
Name=Plasma Bigscreen Input Handler
Comment=Input handler daemon for KDE Plasma Bigscreen
Exec=/usr/bin/plasma-bigscreen-inputhandler
OnlyShowIn=KDE;
X-KDE-autostart-phase=1
X-KDE-Autostart-condition=plasma-bigscreen
AUTOEOF

# Configure system-wide KDE defaults for Plasma Bigscreen
mkdir -p /mnt/etc/xdg
cat >> /mnt/etc/xdg/kdeglobals << 'KDEEOF'

[KDE]
LookAndFeelPackage=org.kde.plasma.bigscreen
KDEEOF

cat > /mnt/etc/xdg/plasmashellrc << 'KDEEOF'
[Shell]
ShellPackage=org.kde.plasma.bigscreen
KDEEOF

cat > /mnt/etc/xdg/ksplashrc << 'KDEEOF'
[KSplash]
Engine=none
Theme=org.kde.plasma.bigscreen
KDEEOF

# User KDE config
mkdir -p "/mnt/home/$USERNAME/.config"
cat > "/mnt/home/$USERNAME/.config/kdeglobals" << 'KDEEOF'
[KDE]
LookAndFeelPackage=org.kde.plasma.bigscreen
KDEEOF

cat > "/mnt/home/$USERNAME/.config/plasmashellrc" << 'KDEEOF'
[Shell]
ShellPackage=org.kde.plasma.bigscreen
KDEEOF

cat > "/mnt/home/$USERNAME/.config/ksplashrc" << 'KDEEOF'
[KSplash]
Engine=none
Theme=org.kde.plasma.bigscreen
KDEEOF
run_chroot chown -R "$USERNAME:$USERNAME" "/home/$USERNAME/.config" 2>/dev/null || true

mkdir -p /mnt/usr/share/wayland-sessions /mnt/usr/share/xsessions
cat > /mnt/usr/share/wayland-sessions/plasma-bigscreen-wayland.desktop << SESSEOF
[Desktop Entry]
Name=Plasma Bigscreen (Wayland)
Comment=Plasma Bigscreen TV Interface by KDE
Exec=/usr/bin/plasma-bigscreen-session
TryExec=/usr/bin/plasma-bigscreen-session
Type=Application
DesktopNames=KDE
SESSEOF

cat > /mnt/usr/share/xsessions/plasma-bigscreen.desktop << SESSEOF
[Desktop Entry]
Name=Plasma Bigscreen
Comment=Plasma Bigscreen TV Interface by KDE
Exec=/usr/bin/plasma-bigscreen-session
TryExec=/usr/bin/plasma-bigscreen-session
Type=Application
DesktopNames=KDE
SESSEOF

# Configure AccountsService for user
mkdir -p /mnt/var/lib/AccountsService/users
cat > "/mnt/var/lib/AccountsService/users/$USERNAME" << ACCTEOF
[User]
Language=
Session=plasma-bigscreen-wayland
XSession=plasma-bigscreen-wayland
SystemAccount=false
ACCTEOF

# SDDM Autologin configuration
mkdir -p /mnt/etc/sddm.conf.d /mnt/etc/pam.d
cat > /mnt/etc/sddm.conf.d/autologin.conf << SDDMEOF
[Autologin]
User=$USERNAME
Session=plasma-bigscreen-wayland
Relogin=false

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Users]
MinimumUid=1000
MaximumUid=60000
RememberLastUser=true
RememberLastSession=true
SDDMEOF
cp -f /mnt/etc/sddm.conf.d/autologin.conf /mnt/etc/sddm.conf

cat > /mnt/etc/pam.d/sddm-autologin << PAMEOF
#%PAM-1.0
auth        required    pam_permit.so
-account    include     system-local-login
-password   include     system-local-login
-session    include     system-local-login
PAMEOF

cat > /mnt/etc/pam.d/sddm << PAMEOF
#%PAM-1.0
auth        include     system-login
-account    include     system-login
-password   include     system-login
-session    include     system-login
PAMEOF

# Hostname & Avahi mDNS
echo "$HOSTNAME" > /mnt/etc/hostname
cat > /mnt/etc/hosts << HOSTSEOF
127.0.0.1	localhost	$HOSTNAME	tubeos	tubeos.local
127.0.1.1	$HOSTNAME
::1		localhost ip6-localhost ip6-loopback
HOSTSEOF

mkdir -p /mnt/etc/avahi/services
cat > /mnt/etc/avahi/avahi-daemon.conf << 'AVAHIEOF'
[server]
host-name=tubeos
domain-name=local
use-ipv4=yes
use-ipv6=yes
check-response-ttl=no
use-iff-running=yes

[publish]
publish-addresses=yes
publish-hinfo=yes
publish-workstation=yes
publish-domain=yes

[reflector]
enable-reflector=no

[rlimits]
AVAHIEOF

cat > /mnt/etc/avahi/services/tubeos-http.service << 'AVAHISERV'
<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
  <name replace-wildcards="yes">Tube OS Web on %h</name>
  <service>
    <type>_http._tcp</type>
    <port>80</port>
    <txt-record>path=/</txt-record>
  </service>
</service-group>
AVAHISERV

cat > /mnt/etc/avahi/services/dockermigrate.service << 'AVAHISERV'
<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
  <name replace-wildcards="yes">DockerMigrate on %h</name>
  <service>
    <type>_http._tcp</type>
    <port>8070</port>
    <txt-record>path=/</txt-record>
  </service>
</service-group>
AVAHISERV

# Remove live installer service from installed target, enable OOTB Welcome Wizard
rm -f /mnt/etc/systemd/system/tubeos-installer.service 2>/dev/null || true
rm -f /mnt/etc/systemd/system/multi-user.target.wants/tubeos-installer.service 2>/dev/null || true
rm -f /mnt/etc/systemd/system/multi-user.target.wants/install-runner.service 2>/dev/null || true
rm -f /mnt/usr/lib/systemd/system/tubeos-installer.service 2>/dev/null || true
rm -f /mnt/usr/lib/systemd/system/install-runner.service 2>/dev/null || true

# Enable first-boot OOTB Welcome Wizard
mkdir -p /mnt/var/lib/tubeos /mnt/usr/lib/systemd/system
touch /mnt/var/lib/tubeos/need-ootb
cp -f /usr/share/tubeos-installer/tubeos-ootb.service /mnt/usr/lib/systemd/system/tubeos-ootb.service 2>/dev/null || true

# Enable target services
run_chroot mkdir -p /var/log/casaos /var/log/tubeos /var/lib/tubeos/conf /var/lib/tubeos/db /var/lib/tubeos/apps /var/lib/tubeos/appstore /run/tubeos /var/run/tubeos /var/run/rclone /usr/share/tubeos/shell 2>/dev/null || true
rm -f /mnt/etc/docker/daemon.json 2>/dev/null || true
run_chroot systemctl disable tubeos-installer install-runner 2>/dev/null || true
run_chroot systemctl set-default graphical.target 2>/dev/null || true
run_chroot systemctl enable sddm NetworkManager avahi-daemon docker rclone tubeos-ootb tubeos-gateway tubeos-message-bus tubeos-user-service tubeos-local-storage tubeos-app-management tubeos dockermigrate 2>/dev/null || true
log "Services, Plasma Bigscreen, and first-boot welcome wizard configured"

# Cleanup
umount -l /mnt/sys/firmware/efi/efivars 2>/dev/null || true
umount -l /mnt/dev/pts 2>/dev/null || true
umount -l /mnt/dev 2>/dev/null || true
umount -l /mnt/sys 2>/dev/null || true
umount -l /mnt/proc 2>/dev/null || true
umount -l /mnt/boot/efi 2>/dev/null || true
umount -l /mnt 2>/dev/null || true

log "INSTALL_DONE"
