[Service]
# Pulsar OS: Auto-sync Btrfs physical resume offset to rEFInd and sysfs before memory dump
ExecStartPre=-/usr/bin/pulsaros-setup-hibernation
ExecStartPre=-/usr/lib/pulsaros/verify-resume-offset
ExecStartPre=-/usr/lib/pulsaros/sleep-progress start
# Pulsar OS: Safe cleanup on resume
ExecStartPost=/usr/lib/pulsaros/sleep-progress end
