#!/bin/bash
# ==============================================================================
# Pulsar OS - Hibernate package removal script
# ==============================================================================
set -e

systemctl daemon-reload || true
exit 0
