[common]
RuntimePath = /var/run/tubeos

[app]
LogPath = /var/log/casaos/
LogSaveName = app-management
LogFileExt = log
AppStorePath = /var/lib/tubeos/appstore
AppsPath = /var/lib/tubeos/apps

[server]
appstore = https://github.com/IceWhaleTech/CasaOS-AppStore/archive/refs/heads/main.zip
appstore = https://github.com/bigbeartechworld/big-bear-casaos/archive/refs/heads/master.zip