[common]
RuntimePath=/var/run/tubeos

[app]
LogPath=/var/log/casaos
LogSaveName=local-storage
LogFileExt=log
DBPath=/var/lib/tubeos/db
ShellPath=/usr/share/tubeos/shell

[server]
USBAutoMount=
EnableMergerFS=false
